### ISSUE TITLE
Atmos tutorial's make build step fails

### ISSUE THREAD

**Issue by oddietaco** [cloudposse/tutorials#9]
## Describe the Bug
When I run `make build` on the tutorial, I get a build error. The error message tells me that it found a preexisting AWS CLI installation. The AWS CLI is not currently installed on my machine.

## Expected Behavior
The `make build` step described in the [Atmos Tutorial](https://docs.cloudposse.com/tutorials/atmos-getting-started/) complete correctly.

## Steps to Reproduce
1. Clone the repo with `git clone git@github.com:cloudposse/tutorials.git`
2. Run `make init`
3. Run `make build`

## Logs
```Building cloudposse/tutorials:latest from ./Dockerfile with [] build args...
Sending build context to Docker daemon  123.4kB
Step 1/19 : ARG VERSION=latest
Step 2/19 : ARG OS=debian
Step 3/19 : ARG CLI_NAME=tutorials
Step 4/19 : FROM cloudposse/geodesic:$VERSION-$OS
 ---> 7d51f804e7a4
Step 5/19 : RUN mv /usr/local/bin/aws /usr/local/bin/aws1 &&     update-alternatives --install /usr/local/bin/aws aws /usr/local/bin/aws1 1
 ---> Using cache
 ---> 53210a954c12
Step 6/19 : ARG AWS_CLI_VERSION=2.1.34
 ---> Using cache
 ---> 81735b57b4d7
Step 7/19 : RUN AWSTMPDIR=$(mktemp -d -t aws-inst-XXXXXXXXXX) &&     curl -sSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-${AWS_CLI_VERSION}.zip" -o "$AWSTMPDIR/awscliv2.zip" &&     cd $AWSTMPDIR &&     unzip -qq awscliv2.zip &&     ./aws/install -i /usr/share/aws/v2 -b /usr/share/aws/v2/bin &&     update-alternatives --install /usr/local/bin/aws aws /usr/share/aws/v2/bin/aws 2 &&     rm -rf $AWSTMPDIR
 ---> Running in 727d66b23fed
Found preexisting AWS CLI installation: /usr/share/aws/v2/v2/current. Please rerun install script with --update flag.
The command '/bin/sh -c AWSTMPDIR=$(mktemp -d -t aws-inst-XXXXXXXXXX) &&     curl -sSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-${AWS_CLI_VERSION}.zip" -o "$AWSTMPDIR/awscliv2.zip" &&     cd $AWSTMPDIR &&     unzip -qq awscliv2.zip &&     ./aws/install -i /usr/share/aws/v2 -b /usr/share/aws/v2/bin &&     update-alternatives --install /usr/local/bin/aws aws /usr/share/aws/v2/bin/aws 2 &&     rm -rf $AWSTMPDIR' returned a non-zero code: 1
make[1]: *** [/home/acox/src/wisp/tutorials/build-harness/modules/docker/Makefile.build:12: docker/build] Error 1
make: *** [Makefile:24: build] Error 2
```

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: WSL (Microsoft Windows [Version 10.0.19041.1052]) with Ubuntu (Ubuntu 20.04.2 LTS)

**Comment by Gowiem** [comment]
@oddietaco Thanks for opening + apologies on this one! Our `geodesic` image version is pointing at `debian-latest` which means we're always keeping up-to-date, but of course things can break. The latest geodesic now installs AWS CLI V2 by default, which means we no longer need to install it as part of the `cloudposse/tutorials` image. We've since removed that in #8 and we're now properly building that image here so you can skip building it yourself: https://hub.docker.com/r/cloudposse/tutorials/tags?page=1&ordering=last_updated 

I'm going to close this as I believe those two things address this. Please feel free to reopen if I'm mistaken or open a new issue and ping me if you run into something else!
